### ISSUE TITLE
put figures in an output dir

### ISSUE THREAD

**Issue by cahartin** [JGCRI/Hector_COMBO#10]

**Comment by abigailsnyder** [comment]
@cahartin created output directory so your runs should save the figures there now

**Comment by cahartin** [comment]
that generates an ouptput dir but the figures are still in the main dir

**Comment by abigailsnyder** [comment]
Dang, not going into the output directory at all? I’ll try to figure it out but that might end up being down to Mac vs pc. Unlike most of the other issues.

**Comment by cahartin** [comment]
ah...wait some of them print there. there are a billion other figures generated somewhere else in the code!

**Comment by cahartin** [comment]
@abigailsnyder  could you tackle this? i think we just need to point it to an output dir rather than the main dir.

**Comment by abigailsnyder** [comment]
@cahartin I can work on it tomorrow (Tues, Jan 7). Does that work?

**Comment by cahartin** [comment]
keep an eye out for a way in which we could have the code loop over all of the SCENGEN models.  Not critical.

**Comment by cahartin** [comment]
HI_R1R2_NoParis_cov_hi1.pdf
HI_R1R2_ParisPlus_prob_hi15.pdf
hi12_bleachdates__NoParis.txt
PctInitCov_hi12_NoParis.txt
